services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: kooky2bidart
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./back
    container_name: laravel_backend
    depends_on:
      - db
    volumes:
      - ./back:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: kooky2bidart
    command: >
      sh -c "
      php artisan migrate:fresh --seed &&
      php-fpm
      "

  frontend:
    build:
      context: ./front
    container_name: angular_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./front:/usr/src/app

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - ./back:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_data:
